name: Cypress tests for CI/CD
on: [push, workflow_dispatch]
env:
  CYPRESS_USERNAME: ${{ secrets.USERNAME }} 
  CYPRESS_PASSWORD: ${{ secrets.PASSWORD }} 
  
jobs:     
 cypress-run:
    runs-on: ubuntu-latest
    steps:
         - name: Checkout
           uses: actions/checkout@v3

         - name: Npm Updates
           run: npm install
           
         - name: Playwright browsers
           run: npx playwright install --with-deps

         - name: Playwright tests
           run: npm run test
           